#!/usr/bin/env bash

set -xeuo pipefail

# the functions to plot
funcs=(
    "Multibody.*?::realizeSubsystemPositionImpl"
    "Multibody.*?::realizeSubsystemTimeImpl"
    "Multibody.*?::realizeVelocityImpl"
    "AbstractIntegratorRep::stepTo"
#    "malloc"
#    "MatrixHelper<double>::updElt"
)

if [[ $# -eq 0 ]]; then
    bes=("simbody" "opensim")
else
    bes=("$@")
fi

for be in ${bes[@]}; do
    extract_callcount callgrind.${be} ${funcs[@]} | grep -v "CALLCOUNT_NOT_FOUND" > "${be}_callcount"
done

plot_callcounts --lhs-name=${bes[0]} --rhs-name=${bes[1]} -o callcount.png ${bes[@]/%/_callcount}

